#!/bin/bash

export MAKEFLAGS="-j$(expr $(nproc) \+ 1)"

function git-update-commit-date {
  local DATE_STR=`date`
  GIT_COMMITTER_DATE="${DATE_STR}" \
    git commit --amend --no-edit --date "${DATE_STR}"
}

function git-sync-origin-with-usptream {
  local ORIGIN_STR="`git remote get-url origin`"
  local UPSTREAM_STR="`git remote get-url upstream`"
  echo "Syncing ${ORIGIN_STR}/master with ${UPSTREAM_STR}/master"
  git push origin upstream/master:master
}

function git-init-with-empty-commit {
  git init . && \
    git commit --allow-empty --message "Initial commit."
}

echo "`date` - bash_aliases."
