# vim: set filetype=sh : */
source ~/.profile

for F in `find ~/.ssh -type f -name "id_rsa"`;
do
  eval `keychain --eval --agents ssh ${F}`
done

# Add nodejs/bin to path at the end.
export PATH="$PATH:~/.npm-global/bin"

echo "`date` - bash profile."
