#!/bin/bash

export MAKEFLAGS="-j$(expr $(nproc) \+ 1)"

function git-update-commit-date() {
  local DATE_STR=`date`
  GIT_COMMITTER_DATE="${DATE_STR}" \
    git commit --amend --no-edit --date "${DATE_STR}"
}

